spring.application.name=nextstep
spring.datasource.url=jdbc:postgresql://pg-1fea26e-nextstep12.g.aivencloud.com:21833/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_iG2QrIbbvm4dOpuq7TQ

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
